### ISSUE TITLE
Stitch problem

### ISSUE THREAD

**Issue by tsudoko** [spillerrec/Overmix#110]
Overmix 56e4ef324353859d6a604db4912b9e631106c495

Some attempts:
https://comfy.moe/dflqwp.png (ordered, default value of the movement slider)
https://comfy.moe/mipmqv.png (recursive, higher value of the movement slider)
https://comfy.moe/jbazso.png (recursive, max value of the movement slider)

Dumps:
https://comfy.moe/ksottz.7z

**Comment by tsudoko** [comment]
Managed to fix it with a lover movement value, sorry

**Comment by spillerrec** [comment]
Good you got it to work. The aligning still needs some improvement as you can see, I have just been a bit too complacent with it.

After getting it to align properly there are still some issues, see: https://comfy.moe/urmzin.png
- At the bottom you will see several dark horizontal lines, this is caused by a slight decolorization of the edges in the input images. It is easy to fix it by just cropping the images, using the "Crop" tab located in the `Modify files` section on the `Files` tab. Use `Apply modifications` on `Everything` in the `Selection` section to actually apply the changes. (It will crop with the specified amount each time you click.)
- The hard color shift is caused by lightning differences. The last 25 images do not contain movement, so the difference ends up being noticeable when taking the average. (Using the `Static difference` render with a single iteration, you can see this more easily: https://comfy.moe/ukeghe.png) To fix it, select the files with the same coordinates (except one) in `Images` and click `Delete`.
- The green edges is an issue in Overmix with YCrCb images containing subsampling due to #41. The easiest way to avoid this is to use the `Convert`->`To RGB` in the same way as you used the crop tool.

After applying those fixes, it will look something like this: https://comfy.moe/ooexem.png

**Comment by tsudoko** [comment]
Thanks for further help! I left the repeated images in to improve quality, but I can't see any glaring artifacts in the final image anyway. I did not know that was the cause of the color shift.
