### ISSUE TITLE
Unknown crash during aligning

### ISSUE THREAD

**Issue by spillerrec** [spillerrec/Overmix#116]
AverageAligner has a tendency to crash sometimes. Seems to be when the comparator is aligning in both directions with a high degree of movement, so it could be that the image dimensions blows up due to bad alignments and allocation fails. Even so, we should catch such errors.

**Comment by spillerrec** [comment]
Of some reason, the `GradientComparator` tries to diff two planes at an offset larger than the image dimensions, causing the range calculation to overflow (go below 0) and give incorrect ranges. A better check should probably be put in place, and we have to identify why `Difference::simpleAlpha()` is called with an invalid offset in the first place.
The commit only prevents the crash by checking for this condition and giving the maximum error value.

**Comment by Mithgol** [comment]
> AverageAligner has a tendency to crash sometimes.

I believe that a newer anime “Uzaki-chan wa Asobitai!” has a sequence of frames that reliably “always” (instead of “sometimes”) causes a crash in Overmix version 0.4.0 alpha 3 on Windows.

Steps to reproduce:

**Step 1.** Unpack https://github.com/spillerrec/Overmix/releases/download/v0.4.0-alpha3/Overmix.v0.4.0-alpha3.win64.7z to an empty folder.

**Step 2.** Unpack 52 PNG files (00006.png, 00007.png, …, 00057.png) from the following four ZIP archives:

[00006-00021.zip](https://github.com/spillerrec/Overmix/files/4908670/00006-00021.zip)

[00022-00032.zip](https://github.com/spillerrec/Overmix/files/4908671/00022-00032.zip)

[00033-00044.zip](https://github.com/spillerrec/Overmix/files/4908672/00033-00044.zip)

[00045-00057.zip](https://github.com/spillerrec/Overmix/files/4908674/00045-00057.zip)

(There has to be four of them because of [GitHub's 15 MB limit.)](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)

**Step 3.** Launch Overmix (unpacked in step 1), open PNG files (unpacked in step 2) in order of their numbering.

**Step 4.** Check the “Comparing” checkbox.

**Step 5.** Set “Movement directions” to “Both”.

**Step 6.** Click the “Align&Draw” button.

Console reports this issue (#116) and then an access violation:

![(screenshot)](https://user-images.githubusercontent.com/1088720/87249532-44e93b00-c468-11ea-904c-f2552bf6e562.png)

(An obvious workaround is to stay on version 0.4.0 alpha 2 until this issue is fixed.)

**Comment by spillerrec** [comment]
Sorry for the delay, I couldn't get the debug build to work on Windows so it had to wait until I booted into Linux. The issue was a bug in the fast preview due to a completely broken alignment. It has some bugs it appears, even when fixing the crash the preview is not correct.
These frames are definitely going to be useful for fixing this issue though, thanks.
