### ISSUE TITLE
Issues when stitching a scrolling video

### ISSUE THREAD

**Issue by jasonTong68** [spillerrec/Overmix#144]
I'm not trying to stitch a anime screenshot, but a scrolling window: 
https://twitter.com/mitsukiyo_5/status/1156788456208470016

![crop locations](https://user-images.githubusercontent.com/30405220/63638049-2e9e8900-c6b6-11e9-8baa-2a0afd8535ac.png)
With ffmpeg, I can crop the video to exclude static elements. I tried 2 different areas: 
1. the entire width, including the center line
2. the right side of the screen, excluding the center line

Neither of these worked, the output is often a mess.
Direction: Horizontal
Allowed movement: 0.75
![fail01](https://user-images.githubusercontent.com/30405220/63638087-73c2bb00-c6b6-11e9-98fc-afebd2be0bb8.png)
![fail01g](https://user-images.githubusercontent.com/30405220/63638088-76251500-c6b6-11e9-83ad-7c443170bbe0.PNG)

Direction: Horizontal
Allowed movement: 0.15
![fail02](https://user-images.githubusercontent.com/30405220/63638090-77eed880-c6b6-11e9-96b3-ad013964713d.png)
![fail02g](https://user-images.githubusercontent.com/30405220/63638091-79200580-c6b6-11e9-89d7-88eac4272296.png)

Should the center line be excluded or not? I'm not sure whether including the line (using area 1) is better, as it gives more information per frame.

Also, I can't figure out the correct settings for overmix to produce correct results

**Comment by spillerrec** [comment]
The best way to deal with static content is to create a mask. Create a white image with the same size as each frame (in Gimp or similar) and mark areas you do not want as black:
![mask](https://user-images.githubusercontent.com/2292170/63639631-0010b600-c696-11e9-8848-fa308096388e.png)
![mpv-shot0001_ noise-L1](https://user-images.githubusercontent.com/2292170/63639695-db690e00-c696-11e9-9aae-abd43f994e3e.png)
This does not only help aligning, but it also prevent such areas for showing up in the rendered image. Minor stuff like the bar in the middle should not pose an issue for aligning the image however.
You can add the mask in the `Files` tab in the `Alpha masks` box. You can then manually set the mask ID in the `Images` box, erm... individually for all 3000+ images... Yeah, not exactly optimal, I will have to do something about that.
The normal approach is to create the mask directly in Overmix using the `Static difference` render together with the `Binarize` and optionally `Dilate` filters in `Postprocessing`. You can then click `Use as mask` to apply it to all frames. This however requires that the image can at least somewhat align, but it works well for removing hardcoded subtitles, etc..

For aligning you were trying the right thing by setting the allowed movement to 0.15, this should be interpreted as the percentage distance relative to image size. The alignment fails because the `Gradient` comparator which finds the offset between two images gives the wrong result. It can sometimes help to increase the `Start level` and `Maximum level`, which is slower but produces better results. (If you are interested, see a few minutes of this [video about gradient decent](https://youtu.be/IHZwWFHWa-w?t=324), increasing the `Start level` increases the amount of "balls" which will be repeated until `Maximum level` if the error is not below `Maximum difference`. The `Brute force` has a ball for each point, but this is obviously *very* slow.)

However even using `Brute force` here fails, so there might be another issue as well. I will have to investigate further to figure out why, but it might be because of the repetitive contents in the image combined with the low video quality.
I did manage to get it aligned using the work-in-progress `Independent` aligner, you can grab the result below:
![independent10](https://user-images.githubusercontent.com/2292170/63639901-bf1aa080-c699-11e9-907b-b697a37e2a4e.png)
The resulting image is only slightly better than the source video however. It still remains a dream of mine to try something like what I did in [Minimizing JPEG artifacts](https://spillerrec.dk/2015/08/minimizing-jpeg-artifacts/) for video... For now adding a bit of sharpness and contrast in your favorite image editor helps a bit.

**Comment by jasonTong68** [comment]
Thanks for the result image, and thanks for working on this program. It is quite useful in many situations.
