### ISSUE TITLE
Upload new release binary

### ISSUE THREAD

**Issue by Scyntrus** [spillerrec/Overmix#151]
Could you upload a new release binary to https://github.com/spillerrec/Overmix/releases ?
I tried setting up the development environment to build it myself but gave up.

**Comment by spillerrec** [comment]
Sorry for the delay, I have been busy and I have changed my development environment since last release so I couldn't reuse the setup from the previous release. Could you check if the release runs properly without DLL errors etc. when starting the program?

https://github.com/spillerrec/Overmix/releases/tag/v0.4.0-alpha3
I haven't worked much on Overmix as my workplace has kept me busy so there are not a lot of changes since last release. Anything in particular you where looking for?

I switched to MSYS2 which was a lot easier to set up (once I found the correct command to install GCC at least). The rest of the dependencies comes by installing them one-by-one with `pacman -S`, no need to compile any libraries manually.

**Comment by Scyntrus** [comment]
Thanks for this!
Running it doesn't cause any DLL errors but I do get some exceptions here and there, but it looks like it still works.
I noticed now that the feature I was looking for actually already exists... but I do feel like it runs faster.

**Comment by Scyntrus** [comment]
I actually thought there were some new features described in the wiki that weren't present in the alpha2 release, but actually the wiki is outdated so the options listed in the wiki don't exist anymore or are renamed.
https://github.com/spillerrec/Overmix/wiki/Manual-%7C-Merging-options

**Comment by Mithgol** [comment]
ZIP and 7-Zip archives currently attached at https://github.com/spillerrec/Overmix/releases/tag/v0.4.0-alpha3 are the same archives (with byte-by-byte equality) that were attached at https://github.com/spillerrec/Overmix/releases/tag/v0.4.0-alpha2 and they're even named with the same “-alpha2” suffix.

They do not look like the new files generated by the newer development environment.

**Comment by spillerrec** [comment]
Well, that is embarrassing... I have edited the release with what I assume are the files I intended to upload.
