### ISSUE TITLE
Can it stitch images in horizontal and vertical directions both.

### ISSUE THREAD

**Issue by ceyxasm** [spillerrec/Overmix#157]
I am working on multiple image stitching where my image is images taken from drone and I need to stitch to create a map. 
However, most of the implementations i saw can only stitch dominantly in one orientation.

**Comment by scribblemaniac** [comment]
Yes, but you for drone footage you would likely be much better off using [OpenDroneMap](https://www.opendronemap.org/).

**Comment by spillerrec** [comment]
Overmix can stitch in both directions, but is very specifically for anime video sources which have exact translations and reusing as much information in each frame to improve final quality. It is not going to perform well with images taken from a camera, due to the camera's FOV causing parallax distortion and small changes in camera angle/rotation will also cause distortion Overmix currently can't handle.

So take a look at OpenDroneMap or other Photogrammetry software like ColMap or Meshroom. Even if you don't want a 3D model as your output, the very first step is usually to estimate the camera position and direction and you can just take that result and use that for your own stitching.
However unless you are doing something very simple like rotating the drone to make a 360 VR image or shooting straight down from very far up to create a satellite like view, you probably want the full 3D model.
