### ISSUE TITLE
dead project? 

### ISSUE THREAD

**Issue by AreFinstad** [spillerrec/Overmix#91]
hmmm is this project dead? 
really like the animated stitching function of it in general and wish it was more complete with usable guides. 
have had this on my machine since June last year and it hasnt had an update since then :(

just wish this tool was more complete with atleast animated stitching and so on.

**Comment by Ryuukishi** [comment]
How is it dead when the latest commit was 3 days ago?

**Comment by spillerrec** [comment]
Yeah, this project is still alive, it is just that I haven't made a release for almost a year. Most of the commits since last release have been for the interface though.

I'm no good at making frequent releases because I want to have completed some sort of milestone, but this is also partly because I don't see anyone using Overmix. I released v0.3.0 because someone asked for a new build ([here](http://spillerrec.dk/2015/05/extracting-an-image-overlay/#comments)), but since then I have not had any feedback at all. (89 of 91 issues on this tracker is by myself.)

So if you are interested in this project and want it to improve, please try to contribute in any of the following ways: (I should add this to the readme I guess...)
- If it currently does not solve all your needs, make a feature request here. If it have already been requested by someone else, feel free to bump it. It doesn't mean it will be done, but I will keep it in mind.
- If you fail to stitch an image properly, create an issue and share the input images somehow. (Or send me an email if you don't want it to be public.) Either I can help find you the right settings, or identify a current limitation of Overmix.
- If you can't figure out how to use some part of the program even after checking the wiki (or even it was just difficult), create a bug report. This mean that either the interface is not intuitive enough, documentation is lacking, or documentation is not clear enough. (I don't have the time to justify write documentation I don't know if anybody is going to read.)

Currently animated stitching is very poor, sometimes it works great, other times the results are useless. I do have an idea on how to improve it, but since nobody voiced their interest and I didn't use it that much, it have been on the back burner.
If you had an issue with animated stitching, share your experiences. Overmix will not improve without feedback!

**Comment by AreFinstad** [comment]
all i can say, Documentations is lacking. the wiki is lacking in many ways, while you do talk about what the options do and such. there isnt really a guide on how to use the program and settings that works for certain things and so on. the UI is fine in itself i guess. could be simpler, im not a dev at all but i do see the usefulness of this program and i do want too use it for many things. 

i do get your side of things tho, this is a quiet project and even your blog site is quiet. i randomly found it when searching for stitching well over two years ago. but i find it hard to do simple things.

say if i have a panning clip (a video or gif or whatever) then export it all to pngs with adobe media encoder and so on. add all of those frames to the Overmix program i would think it would try it best to make it an stitched loop or something. hard to figure it out with lack of documentations. 

like, should i remove alot of the frames? should i leave them in and so on?

stitching image is one thing, many programs does that well already. but animated stitching in the other hand, like you showed in your blog post a good while back is what i look mostly forward too with this program. the other things is great aswell ofc! but that is my main usage is going to be from this program.... for now. 

note that this is just my feedback and how i see things.

**Comment by spillerrec** [comment]
Ok, as I understand this is the case "you never figured out how to use feature X".
I think the main issue is that you expected animation to work out of the box, and that it is not enabled by default. And it will not be enabled by default since it is slow and often do not work.

Did you notice the **Animated** section in **Manual | Merging options**? I see it is out-of-date, as this is now called `Seperate frames` (it is not even spelled right) and it no longer dumps the output to a folder as v0.3.0 now supports animation in the viewer. Or was it not apparent that **Manual | Merging options** explains the `Merging` section in more detail?

So what you have to do is to select `Seperate frames` in the dropbox in the `Merging` box, click `Align`, and hope for the best. If you end up with a 50 frame animation, it obviously failed to do it properly.
Note that this does not align the images, it only tries to detect what frame each image belongs to which. Use the normal `Ordered` or `Recursive` option to align them. Check `On each frame` to align each frame separately, if the animation prevents it from aligning properly otherwise.

Did **Manual | Main Interface** make it clear that you need to actively choose change `Vertical` and `Horizontal` depending on the image you try to stitch? I never intended Overmix to be fully automatic and I might not communicate this properly. Standard settings work great (and very fast) for 95% of stitches, but you do need to modify the settings for the last 5%, for example with animations.

**Comment by spillerrec** [comment]
I released an alpha for version 0.4.0: https://github.com/spillerrec/Overmix/releases/tag/v0.4.0-alpha
It took a bit of time since I haven't been able compile it on my current Windows setup for quite some time.

**Comment by vitormathews** [comment]
Now it's dead :(

**Comment by spillerrec** [comment]
More like I'm dead, I have barely pushed any code on any project to GitHub the last year. :(
